# **Numpy?**

1.  Array Definition
2.  Working with Array
3.  General Functions
4.  Aggregate Functions
5.  Comparison and Boolean logic
6.  Indexing with arrays
7.  Sorting and Linear Algebra

----

----

## How to import and check our numpy version??

In [1]:
import numpy as np # عموما به طور قراردادی از کتابخانهٔ نامپای به این شکل استفاده می‌شود
np.__version__ 

'1.23.3'

# In this Part We talk mostly about
-  ## Array definition and its methods and how they work and why we need array

In [2]:
np.array([1, 2, 3]) # آرایه‌ی یک بعدی شامل 3 عدد

array([1, 2, 3])

---

In [3]:
np.array([[1, 2], # آرایه‌ی دو بعدی 2*3 شامل 6 عدد 
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

---

In [4]:
np.array([[['000', '001'], ['010', '011']], # آرایه‌ی سه بعدی 2*2*2 شامل 8 رشته
          [['100', '101'], ['110', '111']]])
# نوع خانه‌های آرایه‌ی را نشان می‌دهد و dtype
# که نوع این آرایه‌ی می‌شود به معنای رشته یونی‌کد 3 حرفی است <U3

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

---

In [5]:
np.zeros(3) # آرایه‌ی یک بعدی شامل 3 عدد حقیقی برابر صفر

array([0., 0., 0.])

---

In [6]:
np.ones((2, 3)) # آرایه‌‌ی دو بعدی 3*2 شامل 6 عدد حقیقی برابر یک

array([[1., 1., 1.],
       [1., 1., 1.]])

---

In [7]:
np.full((3, 2), '#') # آرایه‌ی دو بعدی 2*3 شامل 6 رشتهٔ '#' یکسان

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

---

In [8]:
np.arange(0, 15, 4) # آرایه‌ی یک بعدی شامل اعداد صحیح پیش از 15 با شروع از 0 و با فاصله 4

array([ 0,  4,  8, 12])

---

In [9]:
np.linspace(0, 20, 5) # آرایه‌ی یک بعدی شامل 5 عدد حقیقی در بازه 0 تا 20 (شامل این دو) با فاصله برابر

array([ 0.,  5., 10., 15., 20.])

---

In [10]:
np.eye(3) # آرایه‌ی دو بعدی 3*3 متناظر با ماتریس همانی (قطر 1 و باقی خانه‌ها 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

In [11]:
np.empty(3) # آرایه‌ی یک بعدی شامل 3 عدد نامشخص (بسته به مقدار داخل حافظه)

array([1., 1., 1.])

---

In [12]:
np.random.random(3) # آرایه‌ی یک بعدی شامل 3 عدد تصادفی از توزیع یکنواخت بین 0 و 1

array([0.86802889, 0.65046792, 0.38101668])

---

In [13]:
np.random.randint(0, 10, (3, 3)) # آرایه‌ی دو بعدی 3*3 شامل اعداد صحیح تصادفی بین 0 تا 9 

array([[3, 6, 0],
       [7, 8, 0],
       [8, 1, 0]])

---

In [14]:
np.random.normal(0, 1, (2, 3)) # آرایه‌ی دو بعدی 3*2 شامل اعداد تصادفی از توزیع نرمال با میانگین 0 و واریانس 1 

array([[ 1.11785968,  0.57644481,  1.27421893],
       [-0.04661015,  0.97218436,  3.13576192]])

---

In [15]:
a = np.random.randint(0, 10, (2, 3))
np.full_like(a, 3) # آرایه‌ی پر از 3 با ابعاد مشابه آرایه ورودی (3*2)

array([[3, 3, 3],
       [3, 3, 3]])

---

![](https://quera.org/qbox/view/un7crtXtLU/full_like.gif)

---

In [16]:
np.array([False, True], dtype='bool_') # نوع مقدار بولی
# کاراکتر _ برای اشاره به نوع داخل نامپای است اما می‌توان آن را برداشت

array([False,  True])

---

In [17]:
np.array([1, 2, 3.14], dtype='int_') # نوع عدد صحیح (عدد سوم تبدیل به 3 می‌شود)

array([1, 2, 3])

---

In [18]:
np.array([2.71828182845, 3.14159265359], dtype='float64') # نوع عدد حقیقی 64 بیتی

array([2.71828183, 3.14159265])

---

In [19]:
np.array([255], dtype='uint8') # نوع عدد صحیح نامنفی 8 بیتی

array([255], dtype=uint8)

---

In [20]:
np.array(['Hello', 'World'], dtype='str_') # نوع رشته

array(['Hello', 'World'], dtype='<U5')

---

In [21]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]], dtype='float64')
print(a)
print('number of dimensions:', a.ndim) # تعداد ابعاد آرایه
print('shape:', a.shape) # اندازه ابعاد آرایه
print('size:', a.size) # تعداد خانه‌های آرایه
print('dtype:', a.dtype) # نوع داده آرایه

[[1. 2.]
 [3. 4.]
 [5. 6.]]
number of dimensions: 2
shape: (3, 2)
size: 6
dtype: float64


---

![](https://quera.org/qbox/view/s1CbjTbEPH/dimensions.PNG)

---

In [22]:
c = np.array(['h', 'e', 'l', 'l', 'o'])
print(c)
print(c.itemsize, 'bytes') # تعداد بایت برای هر خانه آرایه
print(c.nbytes, 'bytes') # تعداد بایت برای کل آرایه

['h' 'e' 'l' 'l' 'o']
4 bytes
20 bytes


---

# **Now it's time to learn Indexing**

In [23]:
a = np.array([5, 1, 8, 4])
print(a)

[5 1 8 4]


In [24]:
print('a[0] =', a[0])
print('a[2] =', a[2])
print('a[-1] =', a[-1])

a[0] = 5
a[2] = 8
a[-1] = 4


---

In [25]:
a = np.random.randint(0, 10, (3, 5))
print(a)

[[4 4 3 3 5]
 [5 1 6 1 6]
 [3 1 8 5 3]]


In [26]:
print('a[2, 3] =', a[2, 3])

a[2, 3] = 5


In [27]:
a[2, 3] = 10
print('a[2, 3] =', a[2, 3])

a[2, 3] = 10


In [28]:
print(a)

[[ 4  4  3  3  5]
 [ 5  1  6  1  6]
 [ 3  1  8 10  3]]


---

# **Slicing??**

In [29]:
a = np.array([0, 1, 2, 3, 4])
print(a)

[0 1 2 3 4]


In [30]:
print(a[:3])
print(a[2:4])
print(a[1:5:2])
print(a[::-1])

[0 1 2]
[2 3]
[1 3]
[4 3 2 1 0]


---

In [31]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
print(a[:2, 1:])

[[1 2]
 [4 5]]


In [33]:
print(a[1:3, ::2])

[[3 5]
 [6 8]]


In [34]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [35]:
print(a[:2, 1])

[1 4]


In [36]:
print(a[2, :])

[6 7 8]


In [37]:
print(a[:, 1])

[ 1  4  7 10]


In [38]:
print(a[2])

[6 7 8]


---

**view and not a copy**

In [39]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_a = a[1:3, 1:]
sub_a[0, 0] = 10
print(a)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


---

**method for copying an array**

In [40]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_copy_a = a[2:4, 1:].copy()
sub_copy_a[0, 0] = 10
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


---

# **Reshaping??**

In [41]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [42]:
print(a.reshape(4, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [43]:
a = np.array([1, 2, 3])
print(a.reshape(3, 1))

[[1]
 [2]
 [3]]


In [44]:
print(a.reshape(1, 3))

[[1 2 3]]


In [45]:
a = np.arange(12)
print(a.reshape(2, -1, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


---

# **Flattening??**

In [46]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a.reshape(-1))

[0 1 2 3 4 5 6 7 8]


---

# **Transpose??**

In [47]:
a = np.arange(8).reshape(2, 4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [48]:
print(a.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


![](https://quera.org/qbox/view/xfWkJ9uk6z/transpose.gif)

In [49]:
a = np.arange(24).reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
np.transpose(a)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

---

In [51]:
a = np.arange(8).reshape(2, 4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [52]:
a.swapaxes(0, 1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

![](https://quera.org/qbox/view/Lx2KUrWiwA/axis.png)

---

# **Concatenate??**

In [53]:
x = np.arange(6).reshape(2, 3)
y = np.arange(6, 12).reshape(2, 3)
z = np.arange(12, 15).reshape(1, 3)
print(x)

[[0 1 2]
 [3 4 5]]


In [54]:
print(y)

[[ 6  7  8]
 [ 9 10 11]]


In [55]:
print(z)

[[12 13 14]]


In [56]:
a = np.concatenate([x, y, z])
print(a,"\n","shape of a is = ",a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 
 shape of a is =  (5, 3)


In [57]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

![](https://quera.org/qbox/view/Yw0nPkHTuR/concatenate.gif)

---

# **Split??**

In [58]:
a = np.arange(10)
x, y, z = np.split(a, [2, 5])
print(x)
print(y)
print(z)

[0 1]
[2 3 4]
[5 6 7 8 9]


In [59]:
a = np.arange(12).reshape(2, 6)
x, y, z = np.split(a, 3, axis=1)
print(x)
print(y)
print(z)

[[0 1]
 [6 7]]
[[2 3]
 [8 9]]
[[ 4  5]
 [10 11]]


![](https://quera.org/qbox/view/SHhG2Vh91J/split.png)

---

....