<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
ابتدا کتابخانه های مورد استفاده را وارد میکنیم و یک ماتریس ایجاد میکنیم
    </font>
</p>

In [36]:
import numpy as np
np.random.seed(1402)
a = np.random.randint(1,10, [5,3])
a

array([[8, 5, 7],
       [2, 2, 7],
       [7, 8, 2],
       [9, 8, 6],
       [3, 8, 8]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
با استفاده از نامپای ایندکس اعدادی که در ماتریس a بزرگتر از 5 هستند را بیابید
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
ماتریس a را به یک ماتریس یک بعدی تبدیل کنید بطوری که تمام عناصر آن باقی بماند
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
کدی بنویسید که ستون دوم ماتریس a را در خروجی مانند زیر در یک ستون نمایش دهد
    </font>
</p>

In [ ]:
# array([[8],
#        [2],
#        [7],
#        [9],
#        [3]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
با استفاده از نامپای یک آرایه تصادفی بسازید گه شامل اعداد ۱ تا ۹ باشد همه اعداد یک تا نه را شامل باشد و عددی تکرار نشود
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
آرایه ای که در مرحله قبل ساختید را از آخر به اول مرتب کنید
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
یک آرایه تصادفی با ۱۵ عضو بسازید که اعداد داخل آن بین صفر تا ۹۹ باشند و بزرگترین عددآن را با منفی ۵ جایگزین کنید
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
یک کد بنویسید که تست کند آیا تمام اعضای یک آرایه نامپای غیرصفر هست یا خیر، 
    </font>
<font face="vazir" size=4 color=#9ebae8>
اگر آرایه شامل صفر نبود True و اگر آرایه شامل صفر بود False را نمایش دهد
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium ">
<font face="vazir" size=4 color=#9ebae8>
یک کد بنویسید که ماتریس a را بگیرد و یک قاب (برد) دور تا دور آن با عدد صفر ایجاد کند مانند زیر:
    </font>
</p>

In [ ]:
input:
[[8 5 7]
 [2 2 7]
 [7 8 2]
 [9 8 6]
 [3 8 8]]

out:
[[0 0 0 0 0]
 [0 8 5 7 0]
 [0 2 2 7 0]
 [0 7 8 2 0]
 [0 9 8 6 0]
 [0 3 8 8 0]
 [0 0 0 0 0]]