# 1. Compute the min/max for each row for a NumPy 2D array

In [ ]:
import numpy as np

Compute the min-by-max for each row for the given 2d NumPy array:

In [ ]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])

Answer:

# 2. How to find all occurrences of an Element in a list

Hint:

indices = [i for i, x in enumerate(my_list) if x == "whatever"]

Answer:

# 3. How would you convert a Pandas DataFrame into a NumPy array?

Answer:

# 4. How to convert a numeric array to a categorical (text) array?

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

< 3 => small

3-5 => medium

'>= 5 => large

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Answer:

# 5. How to find all the local maxima (or peaks) in a 1D array?

Peaks are points surrounded by smaller values on both sides.

Input:

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

Desired Output:

array([2, 5])

Answer:

# 6. How would you reverse a NumPy array?

Answer:

# 7. What does einsum do in NumPy?

Answer:

# 8. What is the difference between Vectorisation vs Broadcasting in NumPy?

Answer:

# 9. What is the difference between flatten and ravel functions in NumPy?

import numpy as np

y = np.array(((1,2,3),(4,5,6),(7,8,9)))

OUTPUT:

print(y.flatten())

[1   2   3   4   5   6   7   8   9]

print(y.ravel())

[1   2   3   4   5   6   7   8   9]

Answer:

# 10. What is the difference between test[:,0] vs test[:,[0]]? When would you use one?

Answer:

# 11. What is the most efficient way to map a function over a NumPy array?

Answer: